name: Create and package executable

on:
    push:
        branches:
            - main
            - create-packaging-workflow

env:
    FORCE_COLOR: "1"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    buildExeOnWindows:
        runs-on: windows-latest
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
            - name: "Setup python 3.10"
              uses: actions/setup-python@v2
              with:
                python-version: 3.10
            - name: "Setup virtual environment"
              run: |
                python -m venv venv
                .\venv\Scripts\activate
            - name: "Install dependencies"
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: "Create executable"
              run: pyinstaller main.py --name "simpleDownloader" --onefile --windowed
            - name: "Create archive artifact"
              run: |
                copy dist\simpleDownloader.exe .
                Compress-Archive -Path "simpleDownloader.exe", "icons" -DestinationPath "simpleDownloader.zip"
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: simpleDownloader-release
                path: simpleDownloader.zip
